### ISSUE TITLE
5.4 Flask Static Files

### ISSUE THREAD

**Issue by pilarrope** [siwells/advanced-webtech#15]
![image](https://user-images.githubusercontent.com/91251358/138253070-9299a201-0e4d-44dd-85e4-1edbb85a2161.png)
It is a bit confusing this function, a bit more of clarification will be beneficial for us.

**Comment by siwells** [comment]
I think I've fixed this in the latest commit/version of the workbook. Take a look at the expanded section 5.4 and let me know if it's better or still needs work.
