### ISSUE TITLE
ConfigParser

### ISSUE THREAD

**Issue by Catalin40479296** [siwells/advanced-webtech#17]
It seems Config parser is not working for me, I'm not sure if it is the case for everybody.
The fix that worked for me was:
 Change Line 1: import ConfigParser  to import configparser
Change Line 16: config = ConfigParser . ConfigParser ()  to config=configparser.ConfigParser()

**Comment by siwells** [comment]
Fixed. I'd actually updated it in the workbook but forgot to update the code example in the repo. Simon
